### ISSUE TITLE
Including Verse References in Embedded Links

### ISSUE THREAD

**Issue by SimonZindo** [GsLogiMaker/my-bible-obsidian-plugin#4]
Greetings, I trust you are doing well. 

On a serious note, thank you for making the bible on obsidian. It is very helpful for biblical study, but there is one thing I would love to add and suggest. 

If I link the passage in the note, only the verse will show, not the reference itself. I have to write the bible reference separately to tell me what verse I am looking at. 

For example, if I link ![[Genesis 1 #1]]. The only thing that will show on my notes is the verse and reference contained in it. To see the Bible reference, I have to link, not embed, which does not work if I want the notes in PDF. 

I am curious to know if I am missing something in the settings for that.

I await your response. again, thank you so much for making the bible.

**Comment by GsLogiMaker** [comment]
One thing you can try is adding the references to the verses in the built Bible.
That would turn your embeded links from this:
![Screenshot from 2024-03-18 11-48-54](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/87501052/374a4091-2c20-4905-a6b1-fe72bee5e3e3)

to this:
![Screenshot from 2024-03-18 11-50-55](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/87501052/724e5695-8e1c-40ea-b557-872e6e61d0a2)

I did this by adding `**{book} {chapter}:{verse}**` to the `Verse body format` setting and rebuilding the Bible. (Can't paste the actual text because of GitHub.)
![Screenshot from 2024-03-18 12-00-40](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/87501052/af95ac05-66c8-440f-9443-54621e7137b3)

The "1" header left in the final result looks ugly, but it should be possible to remove with CSS snippets. However, this solution does require turning the chapter files into a mess.
![Screenshot from 2024-03-18 11-51-20](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/87501052/0e62c0f9-d098-41c0-a694-5d9a2e1be4e9)
But, if this isn't a problem for you then it should work.

Let me know if this helps.

**Comment by SimonZindo** [comment]
Thank you very much. It was really helpful. It worked.  It is exactly what I needed.

One more thing, if it is possible. Can I have the reference displayed before the verse instead of the verse before the reference? I was just wondering; I tried to reverse the code to get the effect, but it didn't work.

But so far, it is what I needed.

**Comment by GsLogiMaker** [comment]
Unfortunately no. The verse is actually the header which makes it possible to link to the specific verse. So if you put the reference before the verse (the header), then it won't be included.
(Sorry for the late response.)

**Comment by SimonZindo** [comment]
Thank you so much. Again. I highly appreciate what you did.

Great stuff!
